import html2pdf from "html2pdf.js"

export async function generateCROReportPDF(report: any) {
  const html = generateReportHTML(report)

  const element = document.createElement("div")
  element.innerHTML = html

  const opt = {
    margin: 10,
    filename: `CRO-Report-${new Date().toISOString().split("T")[0]}.pdf`,
    image: { type: "jpeg", quality: 0.98 },
    html2canvas: { scale: 2 },
    jsPDF: { orientation: "portrait", unit: "mm", format: "a4" },
  }

  return html2pdf().set(opt).from(element).save()
}

function generateReportHTML(report: any): string {
  const score = report.executive_summary?.cro_score || 0
  const wins = report.executive_summary?.biggest_wins || []
  const fixes = report.executive_summary?.top_fixes || []

  return `
    <div style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
      <style>
        body { margin: 0; padding: 0; }
        .header { background: linear-gradient(135deg, #10b981 0%, #0891b2 100%); color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
        .score-box { background: #f0fdf4; padding: 15px; border-radius: 8px; margin: 10px 0; border-left: 4px solid #10b981; }
        .section { margin: 20px 0; page-break-inside: avoid; }
        .section-title { background: #e0f2fe; padding: 10px 15px; border-radius: 6px; font-weight: bold; color: #0c4a6e; margin-bottom: 10px; font-size: 14px; }
        .subsection { margin: 15px 0; }
        .subsection-title { font-weight: bold; color: #0891b2; margin-bottom: 8px; font-size: 13px; }
        .point { margin: 8px 0; padding: 8px 12px; background: #f9fafb; border-left: 3px solid #10b981; border-radius: 4px; font-size: 12px; }
        .point.negative { border-left-color: #ef4444; }
        .chart-row { display: flex; gap: 15px; margin: 10px 0; }
        .chart-item { flex: 1; background: #f3f4f6; padding: 10px; border-radius: 6px; font-size: 12px; }
        .chart-label { font-weight: bold; color: #374151; margin-bottom: 5px; }
        .chart-value { font-size: 18px; font-weight: bold; color: #10b981; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 2px solid #e5e7eb; font-size: 11px; color: #999; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; }
        th { background: #f3f4f6; padding: 8px; text-align: left; font-weight: bold; font-size: 12px; border-bottom: 1px solid #d1d5db; }
        td { padding: 8px; border-bottom: 1px solid #e5e7eb; font-size: 12px; }
        .badge { display: inline-block; padding: 3px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; }
        .badge-green { background: #dcfce7; color: #166534; }
        .badge-red { background: #fee2e2; color: #991b1b; }
      </style>

      <div class="header">
        <h1 style="margin: 0 0 10px 0; font-size: 28px;">CRO Analysis Report</h1>
        <p style="margin: 0; font-size: 14px;">URL: ${report.storeUrl}</p>
        <p style="margin: 5px 0 0 0; font-size: 12px;">Generated: ${new Date(report.createdAt).toLocaleDateString()}</p>
      </div>

      <div class="section">
        <div class="section-title">Executive Summary</div>
        
        <div class="score-box">
          <div style="font-size: 18px; font-weight: bold; color: #10b981; margin-bottom: 5px;">
            CRO Score: ${score}/100
          </div>
          <div style="height: 8px; background: #e5e7eb; border-radius: 4px; overflow: hidden;">
            <div style="width: ${score}%; height: 100%; background: linear-gradient(90deg, #10b981, #0891b2); transition: width 0.3s ease;"></div>
          </div>
        </div>

        <div class="subsection">
          <div class="subsection-title">Biggest Wins</div>
          ${wins.map((win: string) => `<div class="point" style="border-left-color: #10b981;"><strong>✓</strong> ${win}</div>`).join("")}
        </div>

        <div class="subsection">
          <div class="subsection-title">Top Priority Fixes</div>
          ${fixes.map((fix: string) => `<div class="point negative"><strong>⚠</strong> ${fix}</div>`).join("")}
        </div>
      </div>

      ${generatePerformanceSection(report.speed_performance)}
      ${generateHomePageSection(report.homepage)}
      ${generateProductPageSection(report.product_page)}
      ${generateCollectionPageSection(report.collection_page)}
      ${generateCartCheckoutSection(report.cart_page, report.checkout_page)}
      ${generateSEOSection(report.technical_seo)}
      ${generateMobileSection(report.mobile_experience)}
      ${generateTrustSection(report.trust_social_proof)}
      ${generateHeuristicSection(report.heuristic_evaluation)}
      ${generateCompetitorSection(report.competitor_analysis)}
      ${generateActionPlanSection(report.action_plan_90_days)}

      <div class="footer">
        <p style="margin: 0;">This report was automatically generated by ConvertLab. For more details, visit your dashboard.</p>
      </div>
    </div>
  `
}

function generatePerformanceSection(data: any): string {
  if (!data) return ""
  const scores = data.scores || {}
  return `
    <div class="section">
      <div class="section-title">Speed & Performance</div>
      <div class="chart-row">
        <div class="chart-item">
          <div class="chart-label">Lighthouse Performance</div>
          <div class="chart-value">${scores.lighthouse_performance}/100</div>
        </div>
        <div class="chart-item">
          <div class="chart-label">Accessibility</div>
          <div class="chart-value">${scores.lighthouse_accessibility}/100</div>
        </div>
        <div class="chart-item">
          <div class="chart-label">Best Practices</div>
          <div class="chart-value">${scores.lighthouse_best_practices}/100</div>
        </div>
        <div class="chart-item">
          <div class="chart-label">SEO</div>
          <div class="chart-value">${scores.lighthouse_seo}/100</div>
        </div>
      </div>
      <div class="subsection">
        <div class="subsection-title">Issues</div>
        ${(data.issues || [])
          .slice(0, 5)
          .map((issue: string) => `<div class="point negative">⚠ ${issue}</div>`)
          .join("")}
      </div>
      <div class="subsection">
        <div class="subsection-title">Opportunities</div>
        ${(data.opportunities || [])
          .slice(0, 5)
          .map((opp: string) => `<div class="point">✓ ${opp}</div>`)
          .join("")}
      </div>
    </div>
  `
}

function generateHomePageSection(data: any): string {
  if (!data) return ""
  return `
    <div class="section">
      <div class="section-title">Homepage Analysis</div>
      <p style="font-size: 12px; margin: 10px 0; color: #666;">${data.overview}</p>
      <div class="subsection">
        <div class="subsection-title">Issues (${data.issues?.length || 0})</div>
        ${(data.issues || [])
          .slice(0, 5)
          .map((issue: string) => `<div class="point negative">⚠ ${issue}</div>`)
          .join("")}
      </div>
      <div class="subsection">
        <div class="subsection-title">Opportunities (${data.opportunities?.length || 0})</div>
        ${(data.opportunities || [])
          .slice(0, 5)
          .map((opp: string) => `<div class="point">✓ ${opp}</div>`)
          .join("")}
      </div>
    </div>
  `
}

function generateProductPageSection(data: any): string {
  if (!data) return ""
  return `
    <div class="section">
      <div class="section-title">Product Page Analysis</div>
      <p style="font-size: 12px; margin: 10px 0; color: #666;">${data.overview}</p>
      <div class="subsection">
        <div class="subsection-title">Issues (${data.issues?.length || 0})</div>
        ${(data.issues || [])
          .slice(0, 5)
          .map((issue: string) => `<div class="point negative">⚠ ${issue}</div>`)
          .join("")}
      </div>
      <div class="subsection">
        <div class="subsection-title">Opportunities (${data.opportunities?.length || 0})</div>
        ${(data.opportunities || [])
          .slice(0, 5)
          .map((opp: string) => `<div class="point">✓ ${opp}</div>`)
          .join("")}
      </div>
    </div>
  `
}

function generateCollectionPageSection(data: any): string {
  if (!data) return ""
  return `
    <div class="section">
      <div class="section-title">Collection Page Analysis</div>
      <p style="font-size: 12px; margin: 10px 0; color: #666;">${data.overview}</p>
      <div class="subsection">
        <div class="subsection-title">Issues (${data.issues?.length || 0})</div>
        ${(data.issues || [])
          .slice(0, 5)
          .map((issue: string) => `<div class="point negative">⚠ ${issue}</div>`)
          .join("")}
      </div>
      <div class="subsection">
        <div class="subsection-title">Opportunities (${data.opportunities?.length || 0})</div>
        ${(data.opportunities || [])
          .slice(0, 5)
          .map((opp: string) => `<div class="point">✓ ${opp}</div>`)
          .join("")}
      </div>
    </div>
  `
}

function generateCartCheckoutSection(cartData: any, checkoutData: any): string {
  return `
    <div class="section">
      <div class="section-title">Cart & Checkout Analysis</div>
      
      ${
        cartData
          ? `
        <div class="subsection">
          <div class="subsection-title">Cart Page</div>
          <p style="font-size: 12px; margin: 5px 0; color: #666;">${cartData.overview}</p>
          ${(cartData.issues || [])
            .slice(0, 3)
            .map((issue: string) => `<div class="point negative">⚠ ${issue}</div>`)
            .join("")}
        </div>
      `
          : ""
      }
      
      ${
        checkoutData
          ? `
        <div class="subsection">
          <div class="subsection-title">Checkout Page</div>
          <p style="font-size: 12px; margin: 5px 0; color: #666;">${checkoutData.overview}</p>
          ${(checkoutData.issues || [])
            .slice(0, 3)
            .map((issue: string) => `<div class="point negative">⚠ ${issue}</div>`)
            .join("")}
        </div>
      `
          : ""
      }
    </div>
  `
}

function generateSEOSection(data: any): string {
  if (!data) return ""
  return `
    <div class="section">
      <div class="section-title">Technical SEO</div>
      <div class="subsection">
        <div class="subsection-title">Issues (${data.issues?.length || 0})</div>
        ${(data.issues || [])
          .slice(0, 5)
          .map((issue: string) => `<div class="point negative">⚠ ${issue}</div>`)
          .join("")}
      </div>
      <div class="subsection">
        <div class="subsection-title">Opportunities (${data.opportunities?.length || 0})</div>
        ${(data.opportunities || [])
          .slice(0, 5)
          .map((opp: string) => `<div class="point">✓ ${opp}</div>`)
          .join("")}
      </div>
    </div>
  `
}

function generateMobileSection(data: any): string {
  if (!data) return ""
  return `
    <div class="section">
      <div class="section-title">Mobile Experience</div>
      <div class="subsection">
        <div class="subsection-title">Issues (${data.issues?.length || 0})</div>
        ${(data.issues || [])
          .slice(0, 5)
          .map((issue: string) => `<div class="point negative">⚠ ${issue}</div>`)
          .join("")}
      </div>
      <div class="subsection">
        <div class="subsection-title">Opportunities (${data.opportunities?.length || 0})</div>
        ${(data.opportunities || [])
          .slice(0, 5)
          .map((opp: string) => `<div class="point">✓ ${opp}</div>`)
          .join("")}
      </div>
    </div>
  `
}

function generateTrustSection(data: any): string {
  if (!data) return ""
  return `
    <div class="section">
      <div class="section-title">Trust & Social Proof</div>
      <div class="subsection">
        <div class="subsection-title">Issues (${data.issues?.length || 0})</div>
        ${(data.issues || [])
          .slice(0, 5)
          .map((issue: string) => `<div class="point negative">⚠ ${issue}</div>`)
          .join("")}
      </div>
      <div class="subsection">
        <div class="subsection-title">Opportunities (${data.opportunities?.length || 0})</div>
        ${(data.opportunities || [])
          .slice(0, 5)
          .map((opp: string) => `<div class="point">✓ ${opp}</div>`)
          .join("")}
      </div>
    </div>
  `
}

function generateHeuristicSection(data: any): string {
  if (!data) return ""
  return `
    <div class="section">
      <div class="section-title">Heuristic Evaluation</div>
      ${
        data.nielsen
          ? `
        <div class="subsection">
          <div class="subsection-title">Nielsen's Usability Heuristics</div>
          ${(data.nielsen || [])
            .slice(0, 5)
            .map((item: string) => `<div class="point">✓ ${item}</div>`)
            .join("")}
        </div>
      `
          : ""
      }
      ${
        data.fogg
          ? `
        <div class="subsection">
          <div class="subsection-title">Fogg's Behavior Model</div>
          ${(data.fogg || [])
            .slice(0, 5)
            .map((item: string) => `<div class="point">✓ ${item}</div>`)
            .join("")}
        </div>
      `
          : ""
      }
    </div>
  `
}

function generateCompetitorSection(data: any): string {
  if (!data || !data.competitors) return ""
  return `
    <div class="section">
      <div class="section-title">Competitor Analysis</div>
      ${(data.competitors || [])
        .map(
          (comp: any) => `
        <div class="subsection">
          <div class="subsection-title">${comp.name}</div>
          <p style="font-size: 11px; margin: 5px 0; color: #666;"><strong>URL:</strong> ${comp.url}</p>
          ${(comp.key_differences || [])
            .slice(0, 3)
            .map((diff: string) => `<div class="point">✓ ${diff}</div>`)
            .join("")}
        </div>
      `,
        )
        .join("")}
    </div>
  `
}

function generateActionPlanSection(data: any): string {
  if (!data) return ""
  return `
    <div class="section">
      <div class="section-title">90-Day Action Plan</div>
      ${
        data.week_1_2_high_impact
          ? `
        <div class="subsection">
          <div class="subsection-title">Week 1-2: High Impact</div>
          ${(data.week_1_2_high_impact || [])
            .slice(0, 5)
            .map((item: string) => `<div class="point">✓ ${item}</div>`)
            .join("")}
        </div>
      `
          : ""
      }
      ${
        data.days_15_45_medium_impact
          ? `
        <div class="subsection">
          <div class="subsection-title">Days 15-45: Medium Impact</div>
          ${(data.days_15_45_medium_impact || [])
            .slice(0, 5)
            .map((item: string) => `<div class="point">✓ ${item}</div>`)
            .join("")}
        </div>
      `
          : ""
      }
      ${
        data.days_45_90_long_term
          ? `
        <div class="subsection">
          <div class="subsection-title">Days 45-90: Long-term</div>
          ${(data.days_45_90_long_term || [])
            .slice(0, 5)
            .map((item: string) => `<div class="point">✓ ${item}</div>`)
            .join("")}
        </div>
      `
          : ""
      }
    </div>
  `
}
